apiVersion: v1
kind: Service
metadata:
  name: scaly-backend-service
spec:
  selector:
    app: scaly-backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
