apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaly-frontend
  labels:
    app: scaly-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaly-frontend
  template:
    metadata:
      labels:
        app: scaly-frontend
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret
      containers:
        - name: scaly-frontend
          image: registry.git.chalmers.se/courses/dat490/students/2025/dat490-2025-4/scalyshop-v2-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          env:
            - name: BACKEND_HOST
              value: "35.228.180.183"
            - name: BACKEND_PORT
              value: "5000"
